services:
  postgres:
    image: postgres:16
    environment:
      TZ: ${TZ:-America/Toronto}
      POSTGRES_DB: ${POSTGRES_DB:-courtmate}
      POSTGRES_USER: ${POSTGRES_USER:-courtmate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-courtmate}
    ports:
      - "5432:5432"
    volumes:
      - courtmate_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-courtmate} -d ${POSTGRES_DB:-courtmate}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ:-America/Toronto}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_JUDGE_MODEL: ${OPENAI_JUDGE_MODEL:-gpt-4o-mini}
      OPENAI_ROUTER_MODEL: ${OPENAI_ROUTER_MODEL:-gpt-4o-mini}
      
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-courtmate}
      POSTGRES_USER: ${POSTGRES_USER:-courtmate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-courtmate}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      RETRIEVAL_CONFIG_PATH: /app/data/best-retrieval-config.json 
      OPENAI_RERANK_MODEL: ${OPENAI_RERANK_MODEL:-gpt-4o-mini}
      RERANK_CONFIG_PATH: /app/data/best-reranking-config.json

    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
        
    command:
      - sh
      - -c
      - |
        python -m scripts.db_prep &&
        python -m scripts.seed_operational_data &&
        python app.py

  grafana:
    image: grafana/grafana:latest
    environment:
      TZ: ${TZ:-America/Toronto}
      GF_DATE_FORMATS_DEFAULT_TIMEZONE: browser
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - courtmate_grafana_data:/var/lib/grafana
    depends_on:
      postgres:
        condition: service_healthy
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ:-America/Toronto}
      BADMINTON_MATE_API_URL: http://app:5000
    ports:
      - "8501:8501"
    depends_on:
      - app
    command:
      - streamlit
      - run
      - frontend.py
      - --server.address=0.0.0.0
      - --server.port=8501

volumes:
  courtmate_postgres_data:
  courtmate_grafana_data:

  