import time
from pathlib import Path
from typing import Literal

import pandas as pd
from openai import OpenAI
from pydantic import BaseModel, Field

from courtmate.config import (
    OPENAI_API_KEY,
    OPENAI_JUDGE_MODEL,
    OPENAI_MODEL,
)
from courtmate.ingest import load_documents
from courtmate.rag import (
    DOCUMENT_TEMPLATE,
    PROMPT_TEMPLATE,
    llm,
    search,
)


GROUND_TRUTH_PATH = Path(
    "data/ground-truth-retrieval.csv"
)
DETAIL_RESULTS_PATH = Path(
    "data/rag-evaluation-comparison.csv"
)
SUMMARY_RESULTS_PATH = Path(
    "data/rag-prompt-comparison.csv"
)

TOP_K = 5


BASELINE_PROMPT = """
You are Badminton Mate, an assistant for a badminton club.

Answer the USER QUESTION using only the provided CONTEXT.

If the answer is not available in the context, say:
"I don't have enough information in the club knowledge base
to answer that."

Keep the answer concise.

USER QUESTION:
{question}

CONTEXT:
{context}
""".strip()


PROMPT_CANDIDATES = {
    "baseline_prompt": BASELINE_PROMPT,
    "production_prompt": PROMPT_TEMPLATE,
}


class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description=(
            "Brief reasoning about whether the generated "
            "answer matches the original knowledge record."
        )
    )

    score: Literal["good", "bad"] = Field(
        description=(
            "'good' when the generated answer is correct, "
            "complete, and supported; otherwise 'bad'."
        )
    )


JUDGE_INSTRUCTIONS = """
You are evaluating answers produced by a badminton club RAG system.

You will receive:

1. A user question
2. The original knowledge-base record
3. The answer generated by the RAG system

Decide whether the generated answer correctly recovers the
information needed to answer the question.

Rules:

- The generated answer does not need identical wording.
- It must preserve the important factual information.
- It must not contradict the original knowledge record.
- It must not invent prices, schedules, live availability,
  policies, qualifications, locations, or booking status.
- Mark the answer as bad if it misses the main point.
- Mark the answer as bad if it refuses even though the original
  record contains enough information.
- Source formatting and writing style should not affect the score.

Focus on correctness, completeness, and groundedness.
""".strip()


JUDGE_PROMPT = """
USER QUESTION:
{question}

ORIGINAL KNOWLEDGE-BASE RECORD:
{answer_orig}

RAG GENERATED ANSWER:
{answer_llm}
""".strip()


judge_client = OpenAI(
    api_key=OPENAI_API_KEY
)


def build_prompt(
    question: str,
    search_results: list[dict],
    prompt_template: str,
) -> str:
    context = "\n\n".join(
        DOCUMENT_TEMPLATE.format(
            **document
        )
        for document in search_results
    )

    if not context:
        context = (
            "No relevant knowledge-base "
            "documents were found."
        )

    return prompt_template.format(
        question=question,
        context=context,
        conversation_history=(
            "No previous conversation."
        ),
        operational_context=(
            "No live operational data "
            "was requested."
        ),
    )


def generate_answer(
    question: str,
    prompt_template: str,
) -> tuple[str, list[str]]:
    search_results = search(
        query=question,
        num_results=TOP_K,
    )

    prompt = build_prompt(
        question=question,
        search_results=search_results,
        prompt_template=prompt_template,
    )

    answer, _ = llm(
        prompt=prompt,
        model=OPENAI_MODEL,
    )

    retrieved_ids = [
        str(document.get("id"))
        for document in search_results
    ]

    return answer, retrieved_ids


def evaluate_answer(
    question: str,
    answer_orig: str,
    answer_llm: str,
) -> AnswerEvaluation:
    prompt = JUDGE_PROMPT.format(
        question=question,
        answer_orig=answer_orig,
        answer_llm=answer_llm,
    )

    response = judge_client.responses.parse(
        model=OPENAI_JUDGE_MODEL,
        instructions=JUDGE_INSTRUCTIONS,
        input=prompt,
        text_format=AnswerEvaluation,
    )

    if response.output_parsed is None:
        raise RuntimeError(
            "The judge returned no structured result."
        )

    return response.output_parsed


def main() -> None:
    if not GROUND_TRUTH_PATH.exists():
        raise FileNotFoundError(
            f"Ground truth not found: "
            f"{GROUND_TRUTH_PATH}"
        )

    documents = load_documents()

    documents_by_id = {
        str(document["id"]): document
        for document in documents
    }

    ground_truth_dataframe = pd.read_csv(
        GROUND_TRUTH_PATH
    ).fillna("")

    ground_truth = (
        ground_truth_dataframe.to_dict(
            orient="records"
        )
    )

    print(
        f"Documents: {len(documents)}"
    )
    print(
        f"Questions: {len(ground_truth)}"
    )
    print(
        f"Prompt configurations: "
        f"{len(PROMPT_CANDIDATES)}"
    )
    print(
        f"Generation model: {OPENAI_MODEL}"
    )
    print(
        f"Judge model: {OPENAI_JUDGE_MODEL}"
    )

    detailed_rows = []

    total_evaluations = (
        len(ground_truth)
        * len(PROMPT_CANDIDATES)
    )
    current_evaluation = 0

    for configuration, prompt_template in (
        PROMPT_CANDIDATES.items()
    ):
        print(
            f"\nEvaluating: {configuration}"
        )

        for record in ground_truth:
            current_evaluation += 1

            question = str(
                record["question"]
            )
            expected_id = str(
                record["id"]
            )

            document = documents_by_id.get(
                expected_id
            )

            if document is None:
                raise KeyError(
                    f"Document not found: "
                    f"{expected_id}"
                )

            answer_orig = (
                DOCUMENT_TEMPLATE.format(
                    **document
                )
            )

            try:
                answer_llm, retrieved_ids = (
                    generate_answer(
                        question=question,
                        prompt_template=(
                            prompt_template
                        ),
                    )
                )

                evaluation = evaluate_answer(
                    question=question,
                    answer_orig=answer_orig,
                    answer_llm=answer_llm,
                )

                score = evaluation.score
                reasoning = evaluation.reasoning
                error = ""

            except Exception as exception:
                answer_llm = ""
                retrieved_ids = []
                score = "error"
                reasoning = ""
                error = str(exception)

            detailed_rows.append(
                {
                    "configuration": (
                        configuration
                    ),
                    "question": question,
                    "expected_document_id": (
                        expected_id
                    ),
                    "retrieved_ids": (
                        retrieved_ids
                    ),
                    "answer_orig": answer_orig,
                    "answer_llm": answer_llm,
                    "score": score,
                    "reasoning": reasoning,
                    "generation_model": (
                        OPENAI_MODEL
                    ),
                    "judge_model": (
                        OPENAI_JUDGE_MODEL
                    ),
                    "error": error,
                }
            )

            print(
                f"[{current_evaluation}/"
                f"{total_evaluations}] "
                f"{configuration}: "
                f"{score} — {question}"
            )

            time.sleep(0.1)

    detailed_dataframe = pd.DataFrame(
        detailed_rows
    )

    detailed_dataframe.to_csv(
        DETAIL_RESULTS_PATH,
        index=False,
    )

    summary_rows = []

    for configuration in PROMPT_CANDIDATES:
        configuration_results = (
            detailed_dataframe[
                detailed_dataframe[
                    "configuration"
                ] == configuration
            ]
        )

        valid_results = (
            configuration_results[
                configuration_results[
                    "score"
                ].isin(["good", "bad"])
            ]
        )

        good_count = int(
            (
                valid_results["score"]
                == "good"
            ).sum()
        )
        bad_count = int(
            (
                valid_results["score"]
                == "bad"
            ).sum()
        )
        error_count = int(
            (
                configuration_results[
                    "score"
                ] == "error"
            ).sum()
        )

        evaluated_count = (
            good_count + bad_count
        )

        good_rate = (
            good_count / evaluated_count
            if evaluated_count
            else 0.0
        )

        summary_rows.append(
            {
                "configuration": (
                    configuration
                ),
                "good": good_count,
                "bad": bad_count,
                "errors": error_count,
                "good_rate": good_rate,
            }
        )

    summary_dataframe = pd.DataFrame(
        summary_rows
    )

    best_good_rate = (
    summary_dataframe["good_rate"].max()
    )

    best_candidates = summary_dataframe[
        summary_dataframe["good_rate"]
        == best_good_rate
    ].copy()

    minimum_errors = (
        best_candidates["errors"].min()
    )

    best_candidates = best_candidates[
        best_candidates["errors"]
        == minimum_errors
    ]

    if (
        "production_prompt"
        in best_candidates[
            "configuration"
        ].values
    ):
        selected_configuration = (
            "production_prompt"
        )
    else:
        selected_configuration = (
            best_candidates.iloc[0][
                "configuration"
            ]
        )

    summary_dataframe["selected"] = (
        summary_dataframe[
            "configuration"
        ] == selected_configuration
    )

    summary_dataframe.to_csv(
        SUMMARY_RESULTS_PATH,
        index=False,
    )

    print("\nPrompt comparison:")
    print(
        summary_dataframe.to_string(
            index=False
        )
    )

    print(
        f"\nSelected prompt: "
        f"{selected_configuration}"
    )
    print(
        f"Saved detailed results to: "
        f"{DETAIL_RESULTS_PATH}"
    )
    print(
        f"Saved summary to: "
        f"{SUMMARY_RESULTS_PATH}"
    )


if __name__ == "__main__":
    main()

